Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
import numpy as np

In [4]:
a = np.array([i for i in range (12,24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [17]:
#1 massiv
b = a.reshape(6,2)
b

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [19]:
#2 massiv

c = a.reshape(2,6)
c

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [25]:
#3 massiv

d = a[:6].reshape(3,2)
d

array([[12, 13],
       [14, 15],
       [16, 17]])

In [26]:
#4 massiv
e = a[:8].reshape(4,2)
e

In [29]:
#5 massiv
f = a[-6:].reshape(2,3)
f

array([[18, 19, 20],
       [21, 22, 23]])

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).



In [39]:
b1 = a.reshape(4,-1) #-1 for columns
b1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [34]:
c1 =a.reshape(-1,3) # -1 for lines
c1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [36]:
d1 = a.reshape(3, -1) # -1 for columns
d1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
e1 = a.reshape(6,-1)# -1 for columns
e1

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [49]:
f1 = a.reshape(-1,6) #for lines
f1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?



# нет, смотреть примеры ниже. w - 2 axis, y - 1 axis

In [51]:
w = np.array([[0],
             [0],
             [0],
             [0],
             [0]])
w.shape

(5, 1)

In [53]:
y = np.array([i for i in range (5)])
y.shape

(5,)

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения  со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 

In [78]:
import random

g = np.array([random.gauss(0,1) for i in range(12)])

print(g)
massiv = g.reshape(3,4)
massiv

[-0.21343711  1.51298068 -0.27143476 -1.54917105  0.02304577  0.40677697
  0.31775866  0.55973937  0.74776774  0.32905438 -1.11602424  0.35124524]


array([[-0.21343711,  1.51298068, -0.27143476, -1.54917105],
       [ 0.02304577,  0.40677697,  0.31775866,  0.55973937],
       [ 0.74776774,  0.32905438, -1.11602424,  0.35124524]])

Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [80]:
massiv.size

12

In [86]:
massiv1 = massiv.reshape(1,-1)
massiv1.size , massiv1.shape

(12, (1, 12))

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. 

In [96]:
a = np.array([i for i in range(20,-1,-2)])
a, a.size

(array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0]), 11)

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [97]:
b = np.array([i for i in range(20, 1,-2)]).reshape(1,10)
b, b.size

(array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]]), 10)

## разница между a и b в размере 11 и 10 соответсвенно


Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [144]:
a = np.zeros((3,2), dtype = int)
b = np.ones((2,2), dtype=int)

itog = np.vstack((a,b))
print(f'resulting array: \n{itog}, \nsize = {itog.size}')

resulting array: 
[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]], 
size = 10


5. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.

Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.

Получить матрицу At путем транспонирования матрицы A.

Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? 



In [160]:
a = np.array([i for i in range (0,12)])
A = a.reshape(4,3)
print(f'initial 1D a = {a}, \nreshaped to 4x3 \nA = \n{A}')

initial 1D a = [ 0  1  2  3  4  5  6  7  8  9 10 11], 
reshaped to 4x3 
A = 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [156]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [163]:
A.shape[1] == At.shape[0]

True

In [168]:
B = np.dot(A,At)

print(f'resulting array B =  \n{B}, \nsize = {B.size}')

resulting array B =  
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]], 
size = 16


Получится ли вычислить обратную матрицу для матрицы B и почему?

Да. Понятие обратной матрицы существует только для квадратных матриц, матриц «два на два», «три на три» и т.д.
Наша матрица В квадратная 4х4

In [169]:
B.shape

(4, 4)

6. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C. 
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [240]:
import random
random.seed(a=42)

In [241]:
c = np.array([random.randint(0,15) for i in range (0,16)]) # randint generates uniform distibution (ravnomernoe)
# g = np.array([random.gauss(0,1) for i in range(12)])
print(f'c size = {c.size}')
C = c.reshape(4,4)
print(f'C 4x4: \n{C}')

c size = 16
C 4x4: 
[[ 3  0  8  7]
 [ 7  4  3  2]
 [13  1  0  2]
 [ 6  7  0  6]]


In [242]:
D = B + C*10
D

array([[ 35,  14, 103, 102],
       [ 84,  90, 116, 142],
       [153,  96, 149, 232],
       [ 92, 192, 212, 362]])

In [243]:
np.linalg.det(D)

-74068800.00000006

In [244]:
np.linalg.matrix_rank(D)

4

In [245]:
D_inv = np.linalg.inv(D)
D_inv

array([[-5.28400622e-03,  3.14599399e-03,  9.54112933e-03,
        -5.85995723e-03],
       [-1.20180157e-02,  1.93020543e-02, -8.67409760e-03,
         1.37385782e-03],
       [ 1.30832415e-02,  1.72296568e-02, -1.00412049e-02,
        -4.00978550e-03],
       [ 5.50839220e-05, -2.11273843e-02,  8.05629361e-03,
         5.87129804e-03]])

7. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. 
С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [246]:
for i in D_inv:
    for j in range(len(i)):
        if i[j] < 0:
            i[j] = 0
        else:
            i[j] = 1
D_inv

array([[0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 1., 0., 0.],
       [1., 0., 1., 1.]])

In [247]:
np.unique(D_inv) #only 0 and 1s

array([0., 1.])

In [252]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [253]:
C

array([[ 3,  0,  8,  7],
       [ 7,  4,  3,  2],
       [13,  1,  0,  2],
       [ 6,  7,  0,  6]])

In [262]:
#SOLUTION
E = np.where(D_inv==0, C, B)

E

array([[  3,  14,  23,   7],
       [  7,  50,   3, 122],
       [ 23,  86,   0,   2],
       [ 32,   7, 212, 302]])

Задание 2
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [296]:
col1 = [1, 2, 3, 3, 1]
col2 = [6, 8, 11, 10, 7]
a = np.column_stack((col1,col2))
print(f'a = \n{a}')
mean_a = np.mean(a, axis = 0)
print(f'mean_a = {mean_a}')
type(mean_a)

a = 
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
mean_a = [2.  8.4]


numpy.ndarray

In [ ]:
Задание 3
Вычислите массив a_centered, отняв от значений массива а средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

In [313]:
a_centered = np.column_stack([(a[:,0]-mean_a[0]),(a[:,1]-mean_a[1])])
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [314]:
a_centered.shape

(5, 2)

Задание 4
Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [317]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])
a_centered_sp

8.0

In [320]:
N = a_centered.shape[0]
N

5

In [321]:
a_centered_sp / (N-1) # vopros: zachem? kajis chto-to ne ponimau

2.0

Задание 5**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве а. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. 
В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.



In [325]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [324]:
at = a.transpose()
at

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [327]:
at_cov = np.cov(at)
at_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [328]:
at_cov[0,1]

2.0

In [ ]:
# shoditsa s otvetom iz 4-go

In [ ]:
Практическое задание тема NumPy
Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd.
Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные:
[1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price,в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [41]:
import pandas as pd

In [42]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                   'author_name':['Тургенев', 'Чехов', 'Островский']}, columns=['author_id', 'author_name'])

In [43]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [44]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                   'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price': [450, 300, 350, 500, 450, 370, 290]}, columns=['author_id', 'book_title','price'])

In [45]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2 Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [46]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner') 
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [47]:
top5 = authors_price.sort_values(by='price', ascending=False)[:5]  # nu ili .nlargest :)
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price.
В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [55]:
authors_stat = pd.DataFrame(columns=['min_price','max_price', 'mean_price'])
authors_stat

Empty DataFrame
Columns: [min_price, max_price, mean_price]
Index: []

In [57]:
authors_stat['min_price'] = authors_price.groupby('author_name')['price'].min()
authors_stat['max_price'] = authors_price.groupby('author_name')['price'].max()
authors_stat['mean_price'] = authors_price.groupby('author_name')['price'].mean().round(0)
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370       330.0
Тургенев           300        450       367.0
Чехов              450        500       475.0



* Задание 5
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая.
В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.
Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке.Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая",а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями,при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl".Затем загрузите из этого файла датафрейм и назовите его book_info2.Удостоверьтесь, что датафреймы book_info и book_info2 идентичны


In [58]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [59]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [60]:
pd.pivot_table?

In [68]:
import numpy as np
book_info = pd.pivot_table(authors_price, values = 'price', index = ['author_name'], columns = ['cover'], aggfunc = np.sum, fill_value=0)

In [69]:
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [71]:
pd.to_pickle?

In [72]:
pd.to_pickle(book_info, "book_info.pkl")


In [73]:
book_info2 = pd.read_pickle("book_info.pkl")


In [75]:
book_info2 == book_info

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True